The switch from returning HostnameIf from Hostname_if lead to errors like:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, uninitialized constant Puppet::Parser::Functions::HostnameIf
Did you mean?  Hostname_if (file: /etc/puppetlabs/code/environments/production/modules/bsd/manifests/network/interface/vlan.pp, line: 43, column: 24) (file: /etc/puppetlabs/code/environments/production/modules/profile/manifests/network.pp, line: 53) on node ...

This was seen on OpenBSD with Puppet 5.5.8 to 5.5.16 etc.
in combination with Ruby 2.5.3 to 2.6.3